Portfolio: setup and mobile first
Bupilipili/MY-PORTFOLIO pull request #1
Opened 2023-05-30 14:05 UTC by Bupilipili

In this branch.

-Added MIT.md file 
-Added the style.css file
-Updated the style.css file
-Added the index.html file
-Added linters file
-Added features file
-Updated the index.html file

2023-05-30 18:19 UTC, christianbiring1 requested changes
Hi @Bupilipili , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://github.com/Bupilipili/MY-PORTFOLIO/assets/97100091/f123430e-816a-40d6-9648-362baaab9e7e)
## Highlights
- [ ] Great job on using the list element for your social icons :1st_place_medal: 
- [x] Great job on making your page more semantic as much as possible :+1: 
- [ ] All linters checks are passing :+1: 

## Required Changes ♻️
- [ ] Kindly make sure your PR has a descriptive `title` telling what changes have been introduced in the project.
Hint: `Portfolio: setup and mobile first` would sound more descriptive than `My portfolio Project`
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 18:19 UTC, christianbiring1 commented on index.html
> +               <h2 id="head2">I’m a software <br> developer</h2>
- [x] Kindly make sure all this text is inside an `h1` element to keep your markup semantic :+1: You may consider grabbing the green text in a span like so:

```html
<h1 id="head1">Hey there.<br> I’m Erick.<br>
     <span id="head2">I’m a software <br> developer</span>
</h1>
```
THis is because we only change the heading when we have a subtitle. and in this case, all the text right here constitute one headline

2023-05-30 18:19 UTC, christianbiring1 commented on index.html
> +           <img id="img" src="/features/images/Disabled.png">
- [ ] Kindly make sure you use the correct path for your images as you may notice how this image is not showing.

![image](https://github.com/Bupilipili/MY-PORTFOLIO/assets/97100091/664a5fe6-a411-420b-83ea-2949fbdb843f)
Hint: You may consider adding the dot to specify the root: `<img id="img" src="./features/images/Disabled.png">`

2023-05-30 18:19 UTC, christianbiring1 commented on index.html
> +            I can help you build a product, feature or website Look through some of my work and experience! If you like what you see and have a project you need coded,
- [x] Kinldy make sure you stick to the design as much as possible. As you may notice how your layout doesn't look quite similar to the original template provided in Figma.

### Original template :point_down: 
![image](https://github.com/Bupilipili/MY-PORTFOLIO/assets/97100091/21bf0960-de88-4189-9613-63540f8620e4)

### Your design :point_down: 
![image](https://github.com/Bupilipili/MY-PORTFOLIO/assets/97100091/5c88ca62-dfb6-4990-ad5d-2c93b4da6473)
hint: `You may consider adding the background image as is the case in the original design`

2023-05-31 09:28 UTC, Owusu-Desmond approved these changes
Hi @Bupilipili , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 09:34 UTC, merged