Portfolio: setup and mobile first
Bupilipili/MY-PORTFOLIO pull request #2
Opened 2023-05-31 10:50 UTC by Bupilipili

In this branch.

-Updated the style.css file
-Updated the index.html file

2023-05-31 11:01 UTC, wayungi reviewed
Hi <STUDENT_MENTION>, 
![image](https://user-images.githubusercontent.com/99656687/224543512-ddbefa59-dc68-47c2-b7fe-f55acdacd3eb.png)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌ ❌ 

- [ ] You have submitted a project that is invalid. please remove all instructions & comments from your readme. Clue: they begin with `>`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit.

2023-05-31 16:22 UTC, Strangeal requested changes
Hi @Bupilipili, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                  <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                   <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                   <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                   <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +                   <div class="item2">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +        <div id="content2"><p class="works">My Recent Works</p>
- [ ] Kindly consider using a header tag `hx` eg `h2, h3, h4, h5, h6` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 16:22 UTC, Strangeal commented on index.html
> +       <p class="about">About me</p>
- [ ] Kindly consider using a header tag `hx` eg `(h2, h3, h4, h5, h6)` for the title of each card as it's semantically correct and also helps make your website accessible and SEO friendly.

2023-05-31 21:06 UTC, tufoinnkuo10 requested changes
Hi @Bupilipili 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally


Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-05-31 21:06 UTC, tufoinnkuo10 commented on index.html
> +        <div id="content2"><p class="works">My Recent Works</p>
- [ ] please, maybe you forgot. Like the previous reviewer noted, kindly make the `my recent works` title an `hx`

2023-06-01 05:18 UTC, emmiiorji approved these changes
Hi @Bupilipili, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://github.com/Kccendana/portfolio_project/assets/20554583/a4207e93-a53d-4248-af4f-a42e6c2e677c'/>
</div>


## Good Highlights✔️

- Requested change has been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 07:13 UTC, merged